# Airflow executor
executor: "KubernetesExecutor"

# Images
images:
  airflow:
    repository: my-dags
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent
    
postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
    tag: "17.6.0-debian-12-r4"
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/shaswat08/databricks-airflow-project.git
    branch: main
    rev: HEAD
    ref: main
    depth: 1
    maxFailures: 0
    subPath: "dags"
    credentialsSecret: git-credentials

logs:
  persistence:
    enabled: true
    storageClassName: manual
    existingClaim: airflow-logs-pvc 

