apiVersion: v1 
kind: Secret 
metadata:
  name: git-credentials
  namespace: airflow 
data:
  GITSYNC_USERNAME: c2hhc3dhdA==
  GITSYNC_PASSWORD: Z2hwX056RE5DaE5Ha3RGMEJ0bTFWWEFsRHhOS1BaQjFIODFIbHdxQQ==
  GIT_SYNC_USERNAME: c2hhc3dhdA==
  GIT_SYNC_PASSWORD: Z2hwX056RE5DaE5Ha3RGMEJ0bTFWWEFsRHhOS1BaQjFIODFIbHdxQQ==