apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: E:\Programming\Python\Data\databricks-airflow-project\tmp\logs
        containerPath: /mnt/airflow-data/logs