apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv 
spec:
  storageClassName: manual 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/airflow-data/logs 