name: Push Airflow image to ECR 
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS creds 
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: ap-southeast-2
      - name: Login to ECR 
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          IMAGE_NAME=my-dags
          docker build --pull --tag ${{ secrets.ECR_REGISTRY }}:$IMAGE_TAG -f cicd/Dockerfile .
          docker push ${{ secrets.ECR_REGISTRY }}:$IMAGE_TAG